stages:
  - build_tag_and_push

variables:
  PUSH_REPO: mershab99
  USE_BAZEL_VERSION: "5.1.1"
  DOCKER_DIND_IMAGE: "docker:20.10.16-dind"
  DOCKER_CLIENT_IMAGE: "docker:20.10.16"
  TAR_FILE_FOLDER: ".docker/"
  TAR_FILE_PATH: "/"
  BUILD_DOCKER_IMAGE_VERSION: "v2.4.1-1.17"
  BUILDPACKS_BASE_REPO: "openfunctiondev"
  BUILDER_BASE_REPO: "openfunction"
  IMAGE_RUN_NAME: "buildpacks-run-go"
  IMAGE_BUILD_NAME: "buildpacks-go117-build"
  IMAGE_BUILDER_NAME: "builder-go"

build_tag_and_push_images:
  stage: build_tag_and_push
  image: 
    name: "$DOCKER_CLIENT_IMAGE"
      #entrypoint: [""]
  variables:
    BASE_IMAGE_BUILD: "$BUILDPACKS_BASE_REPO/$IMAGE_BUILD_NAME:$BUILD_DOCKER_IMAGE_VERSION"
    BASE_IMAGE_RUN: "$BUILDPACKS_BASE_REPO/$IMAGE_RUN_NAME:$BUILD_DOCKER_IMAGE_VERSION"
    BASE_IMAGE_BUILDER: "$BUILDER_BASE_REPO/$IMAGE_BUILDER_NAME:$BUILD_DOCKER_IMAGE_VERSION"
    PUSH_IMAGE_BUILD: "$PUSH_REPO/$IMAGE_BUILD_NAME:$BUILD_DOCKER_IMAGE_VERSION"
    PUSH_IMAGE_RUN: "$PUSH_REPO/$IMAGE_RUN_NAME:$BUILD_DOCKER_IMAGE_VERSION"
    PUSH_IMAGE_BUILDER: "$PUSH_REPO/$IMAGE_BUILDER_NAME:$BUILD_DOCKER_IMAGE_VERSION"
  services:
    - name: "$DOCKER_DIND_IMAGE"
  before_script:
    - apk add --no-cache curl bash tar g++ unzip zip python3 py3-pip
    - curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.34.2/pack-v0.34.2-linux.tgz" | tar -C /usr/local/bin/ --no-same-owner -xzv pack
    - apk add bazel5 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
    - curl -LO https://github.com/GoogleContainerTools/container-structure-test/releases/latest/download/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && mkdir -p $HOME/bin && export PATH=$PATH:$HOME/bin && mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test
    - docker info
    #- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    # USE PUSH REPO AS USERNAME because on dockerhub it is the same
    - docker login -u "$PUSH_REPO" -p "$PUSH_REGISTRY_PASSWORD"
  script:
    - bazel run //builders/go117/stack:build
    #- docker load < "$BASE_IMAGE_BUILD"
    - docker tag "$BASE_IMAGE_BUILD" $PUSH_IMAGE_BUILD
    - bazel build //builders/go117:builder.image
    - echo "Sucessfully built images '$BASE_IMAGE_BUILD','$BASE_IMAGE_RUN','$BASE_IMAGE_BUILDER'"

      #- docker tag "$BASE_IMAGE_BUILD" "$PUSH_IMAGE_BUILD"
    - docker tag $BASE_IMAGE_RUN $PUSH_IMAGE_RUN
    - docker tag $BASE_IMAGE_BUILDER $PUSH_IMAGE_BUILDER
    - echo "Pushing '$PUSH_IMAGE_BUILD'"
    - docker push $PUSH_IMAGE_BUILD
    - echo "Pushing '$PUSH_IMAGE_RUN'"
    - docker push $PUSH_IMAGE_RUN
    - echo "Pushing '$PUSH_IMAGE_BUILDER'"
    - docker push $PUSH_IMAGE_BUILDER
    - echo "Successfully tagged and pushed images '$PUSH_IMAGE_BUILD','$PUSH_IMAGE_RUN','$PUSH_IMAGE_BUILDER'"


